server {
    listen 80;
    listen [::]:80;

    server_name api.aroundtw.mooo.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name api.aroundtw.mooo.com;

    ssl_certificate /etc/letsencrypt/live/aroundtw.mooo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aroundtw.mooo.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    access_log /var/log/nginx/around-api.access.log;
    error_log /var/log/nginx/around-api.error.log;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;

        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}

server {
    listen 80 default_server;
    listen [::]:80 default_server;

    server_name aroundtw.mooo.com www.aroundtw.mooo.com;

    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl default_server;
    listen [::]:443 ssl default_server;

    server_name aroundtw.mooo.com www.aroundtw.mooo.com;

    ssl_certificate /etc/letsencrypt/live/aroundtw.mooo.com/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/aroundtw.mooo.com/privkey.pem;
    include /etc/letsencrypt/options-ssl-nginx.conf;
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

    root /var/www/around-frontend;
    index index.html;

    access_log /var/log/nginx/around-frontend.access.log;
    error_log /var/log/nginx/around-frontend.error.log;

    location / {
        try_files $uri $uri/ /index.html;
    }
}
